# Generated by Django 4.2.3 on 2023-11-08 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinary_Actions',
            fields=[
                ('Case_No', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Date_of_Hearing', models.DateField()),
                ('Penance_Type', models.CharField(max_length=50)),
                ('Penance_Details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('Incident_No', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Date_of_Occurence', models.DateField()),
                ('Location', models.CharField(max_length=5)),
                ('Descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Stud_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('Dept', models.CharField(max_length=45)),
                ('Levl', models.IntegerField()),
                ('Phone_No', models.IntegerField()),
                ('Next_of_Kin', models.CharField(max_length=50)),
                ('Next_of_Kin_Phone_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('Record_No', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Case_Status', models.CharField(max_length=50)),
                ('Case_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disciplinary_actions')),
                ('Incident_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.incidents')),
                ('Stud_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('Notification_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Case_Subject', models.CharField(max_length=5)),
                ('Details', models.TextField()),
                ('Case_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disciplinary_actions')),
                ('Incident_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.incidents')),
                ('Stud_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
        ),
        migrations.AddField(
            model_name='incidents',
            name='Stud_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('Evidence_No', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Ev_Type', models.CharField(max_length=15)),
                ('Details', models.TextField()),
                ('Incident_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.incidents')),
            ],
        ),
        migrations.AddField(
            model_name='disciplinary_actions',
            name='Incident_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.incidents'),
        ),
        migrations.AddField(
            model_name='disciplinary_actions',
            name='Stud_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students'),
        ),
    ]
