# Generated by Django 4.2.3 on 2023-11-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_students_next_of_kin_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='Location',
            field=models.CharField(max_length=15),
        ),
    ]
