# Generated by Django 4.2.3 on 2023-11-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_incidents_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='Ev_Type',
            field=models.CharField(max_length=30),
        ),
    ]
