# Generated by Django 4.2.3 on 2023-11-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_evidence_ev_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
