# Generated by Django 4.2.3 on 2023-11-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_students_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Stud_ID',
            field=models.IntegerField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
