# Generated by Django 4.2.3 on 2023-11-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_stud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='Case_Subject',
            field=models.CharField(max_length=30),
        ),
    ]
