# Generated by Django 4.2.3 on 2023-11-17 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_notifications_case_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='Stud_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stud_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
