# Generated by Django 4.2.3 on 2023-11-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_evidence_stud_id_alter_student_stud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='Stud_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
