# Generated by Django 4.2.3 on 2023-11-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_evidence_stud_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='Stud_ID',
        ),
    ]
