# Generated by Django 4.2.3 on 2023-11-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_evidence_stud_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
