# Generated by Django 4.2.3 on 2023-11-17 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('Evidence_No', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Ev_Type', models.CharField(max_length=30)),
                ('Details', models.TextField()),
                ('Incident_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.incidents')),
                ('Stud_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
