# Generated by Django 4.2.3 on 2023-11-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='Stud_ID',
        ),
    ]
