# Generated by Django 4.2.3 on 2023-11-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_evidence_stud_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=111111, max_length=6),
            preserve_default=False,
        ),
    ]
