# Generated by Django 4.2.3 on 2023-11-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
